### PR TITLE
Avoid blocking iteration on large collections

### PR DESCRIPTION
**Pull request by jden**
Iterating over large collections with native methods like Array.prototype.forEach
is a blocking operation, and will cause the server to become unresponsive to
other messages and events until finished. Relying on Node.js EventEmitters with
a high number of listeners has the same effect, since listeners are called
synchronously.

This PR is the first of a larger body of work to ensure non-blocking operation
for expensive tasks, such as iterating over all ClientSessions or Resources.
The [`nonblocking`](https://www.npmjs.com/package/nonblocking) module will help
in correctly adapting code to be non-blocking without affecting readability or
expresivity.

This PR:
- changes relationship of PresenceManager, Sentry, and Server so that
  PresenceManager does not register an event listener for Sentry.ondown.
  Instead, the Server has a single Sentry.ondown listener, which then fans
  out over Presence resources to appropriately clean up ClientSessions from
  the Sentry that went down. Fan out is done using `nonblocking`.
- Adds a Server `profiling` event to measure times for various operations. The
  first place it's used is to measure `_onSentryDown`.
- Uses `nonblocking` for handling unsubscribing from Resources on ClientSession end
- Improves test coverage
- Minorly cleans up Server setup functions (more work needed here in the future)

References
========
- [RADAR-637](https://zendesk.atlassian.net/browse/RADAR-637)

Required
========
- [ ] :+1: from @zendesk/radar

Risks
========
- Low: overall time to process onSentryDown and onClientSessionEnd will increase, although
  it will no longer block the process
- Low: Some code may incorrectly depend on previous synchronous behavior for ordering of effects.
  Some tests had to be updated. If any, this should be detectable in integration testing.

### CODE REVIEW

**Comment by vanchi-zendesk** [comment]
what happened to the original branch? Why all new code?

**Comment by jden** [comment]
After spending an hour blindly trying to get those tests passing, I re-did it in small increments keeping the tests green the whole way.

**Comment by vanchi-zendesk** [comment]
Makes sense. Will take a look later on.

**Comment by vanchi-zendesk** [comment]
:+1: on green

**Pull request merged**
